[MNG-5456] Incorrect exception handling in parallel build

-            result = processResult( new DefaultMavenExecutionResult(), e );
+            result = addExceptionToResult(new DefaultMavenExecutionResult(), e);
-            result = processResult( new DefaultMavenExecutionResult(), e );
+            result = addExceptionToResult(new DefaultMavenExecutionResult(), e);
-                processResult( new DefaultMavenExecutionResult(),
-                               new InternalErrorException( "Internal error: " + e, e ) );
+                addExceptionToResult(new DefaultMavenExecutionResult(),
+                        new InternalErrorException("Internal error: " + e, e));
-            return processResult( result, e );
+            return addExceptionToResult(result, e);
-            return processResult( result, e );
+            return addExceptionToResult(result, e);
-            return processResult( result, e );
+            return addExceptionToResult(result, e);
-            return processResult( result, e );
+            return addExceptionToResult(result, e);
-            return processResult( result, e );
+            return addExceptionToResult(result, e);
-            return processResult( result, error );
+            return addExceptionToResult(result, error);
-            return processResult( result, e );
+            return addExceptionToResult(result, e);
-            return processResult( result, e );
+            return addExceptionToResult(result, e);
-            return processResult( result, session.getResult().getExceptions().get( 0 ) );
+            return addExceptionToResult(result, session.getResult().getExceptions().get(0));
-    private MavenExecutionResult processResult( MavenExecutionResult result, Throwable e )
+    private MavenExecutionResult addExceptionToResult(MavenExecutionResult result, Throwable e)

UPD42 UPD42 UPD42 UPD42 UPD42 UPD42 UPD42 UPD42 UPD42 UPD42 UPD42 UPD42 UPD42