GEODE-1557: Not logging BucketNotFoundException

Not logging BucketNotFoundException as an error in LuceneEventLister and added
a test shouldIgnoreBucketNotFoundException to verify it

This closes #168

+import com.gemstone.gemfire.internal.cache.partitioned.Bucket;
-        
+
-      
+
-    } catch(IOException | BucketNotFoundException e) {
+    } catch(BucketNotFoundException e) {
+      logger.debug("Bucket not found while saving to lucene index: " + e.getMessage());
+      return false;
+    } catch(IOException e) {

INS26 INS40 INS12 INS44 INS8 MOV43 INS42 INS21 INS41 MOV43 INS32 INS9 INS42 INS42 INS27 INS45 INS32 INS42 INS42 DEL84