GEODE-5283: Client transaction fails with TransactionException: GemFireInternalException

Modified the exception returned to include a CacheClosedException as the cause
and added error handling for this in the reply-processor code

Added a test for this error handling.

This closes #2020

+import org.apache.geode.cache.TransactionDataNodeHasDepartedException;
-    public Set waitForKeys() {
+    public Set waitForKeys(ReplyProcessor21 responseProcessor) {
-        waitForRepliesUninterruptibly();
+        responseProcessor.waitForRepliesUninterruptibly();
+        if (e.getCause() instanceof RemoteOperationException) {
+          if (e.getCause().getCause() instanceof CancelException) {
+            throw new TransactionDataNodeHasDepartedException("Node departed while fetching keys");
+          }
+        }

INS26 INS40 INS44 INS43 INS42 INS42 INS25 INS42 INS62 INS8 INS32 INS43 INS25 INS42 INS42 INS42 INS62 INS8 INS32 INS43 INS53 INS32 INS42 INS42 INS14 INS42 INS42 INS43 INS45 INS42